### ISSUE TITLE
fixing a few elements

### ISSUE THREAD

**Issue by Raaydon** [sheeepdev/nordhub#1]
if you add this code then it will get rid of the black bar at the top and bottom of the screen :)

BEFORE:
![before](https://user-images.githubusercontent.com/69201936/122459612-05489e80-cfa9-11eb-995f-15f732de2691.png)

AFTER:
![after](https://user-images.githubusercontent.com/69201936/122459608-04b00800-cfa9-11eb-842f-50b778b095d2.png)

CODE:
`.hx_page-header-bg {
    background-color: transparent;
}
[data-color-mode] {
    color: var(--color-text-primary);
    background-color: transparent;
}`

**Comment by sheeepdev** [comment]
Hey! I do not have this issue, but I will add the code, sure.

**Comment by Raaydon** [comment]
> Hey! I do not have this issue, but I will add the code, sure.

might be something to do with light/dark mode enabled?
I have dark mode enabled on GitHub so that could be the cause

**Comment by sheeepdev** [comment]
> > Hey! I do not have this issue, but I will add the code, sure.
> 
> might be something to do with light/dark mode enabled?
> I have dark mode enabled on GitHub so that could be the cause

Nope, I have it enabled too. (dark mode)

**Comment by Raaydon** [comment]
> > > Hey! I do not have this issue, but I will add the code, sure.
> > 
> > 
> > might be something to do with light/dark mode enabled?
> > I have dark mode enabled on GitHub so that could be the cause
> 
> Nope, I have it enabled too. (dark mode)

not sure what the issue is then

**Comment by sheeepdev** [comment]
> > > > Hey! I do not have this issue, but I will add the code, sure.
> > > 
> > > 
> > > might be something to do with light/dark mode enabled?
> > > I have dark mode enabled on GitHub so that could be the cause
> > 
> > 
> > Nope, I have it enabled too. (dark mode)
> 
> not sure what the issue is then

Actually, sorry. I just remembered. I have the changes locally so I do not have the issue, I forgot to push the code on GitHub! Sorry.

**Comment by Raaydon** [comment]
> > > > > Hey! I do not have this issue, but I will add the code, sure.
> > > > 
> > > > 
> > > > might be something to do with light/dark mode enabled?
> > > > I have dark mode enabled on GitHub so that could be the cause
> > > 
> > > 
> > > Nope, I have it enabled too. (dark mode)
> > 
> > 
> > not sure what the issue is then
> 
> Actually, sorry. I just remembered. I have the changes locally so I do not have the issue, I forgot to push the code on GitHub! Sorry.

don't worry about it
the style looks good btw :)

**Comment by sheeepdev** [comment]
Thanks, working hard on it :)
